const lang = document.querySelector('#lang');
const original = new Map();
const selectors = ['header nav a','.actions .btn','.hero-lead','.cta .btn','.cta .ghost','.statement p','#features article p','.ai-copy h2','.ai-copy h3','.ai-copy p','.ai-copy li','.results .kicker','.results-head h2','.results-head p','.quote b','.control-copy p','.pricing-head h2','.pricing-head p','.pricing h3','.pricing article > span','.pricing article > p','.pricing article > a','.best','.saving','.faq h2','.faq summary','.faq details p','footer b','footer a'];
const nodes = [...document.querySelectorAll(selectors.join(','))];
nodes.forEach((el,i)=>{el.dataset.i18n=i; original.set(i,el.innerHTML)});
const T={
 en:['Features','GOAT PRO','Pricing','FAQ','Download app','One app for training, nutrition, progress and GOAT AI. Everything you need to stay consistent.',' &nbsp; Download on the App Store','▶ &nbsp; See features','Training. Nutrition. Progress. AI. One coherent system instead of scattered tools.','Plans, sets, RIR, rest timers and exercise history in one place.','Calories, macros, meals and your daily balance — without chaos.','Weight, measurements, consistency, volume, PRs and reports.','Workout, Diet, Meal Scan and analysis help you move to action faster.','Your personal trainer.<br><span>In the app.</span>','PLAN. ANALYZE. ACT.','AI that understands your training, nutrition and goals. It creates plans, analyzes progress and gives concrete guidance.'],
 de:['Funktionen','GOAT PRO','Preise','FAQ','App laden','Eine App für Training, Ernährung, Fortschritt und GOAT AI. Alles, was du brauchst, um konsequent zu bleiben.',' &nbsp; Im App Store laden','▶ &nbsp; Funktionen ansehen','Training. Ernährung. Fortschritt. AI. Ein zusammenhängendes System statt vieler einzelner Tools.'],
 fr:['Fonctions','GOAT PRO','Tarifs','FAQ','Télécharger l’app','Une seule app pour l’entraînement, la nutrition, les progrès et GOAT AI. Tout pour rester régulier.',' &nbsp; Télécharger sur l’App Store','▶ &nbsp; Voir les fonctions','Entraînement. Nutrition. Progrès. IA. Un système cohérent au lieu de plusieurs outils.'],
 it:['Funzioni','GOAT PRO','Prezzi','FAQ','Scarica app','Un’unica app per allenamento, alimentazione, progressi e GOAT AI. Tutto ciò che serve per essere costanti.',' &nbsp; Scarica da App Store','▶ &nbsp; Scopri le funzioni','Allenamento. Alimentazione. Progressi. AI. Un unico sistema coerente.'],
 es:['Funciones','GOAT PRO','Precios','FAQ','Descargar app','Una sola app para entrenamiento, nutrición, progreso y GOAT AI. Todo lo necesario para mantener la constancia.',' &nbsp; Descargar en App Store','▶ &nbsp; Ver funciones','Entrenamiento. Nutrición. Progreso. IA. Un sistema coherente en lugar de herramientas separadas.'],
 pt:['Funcionalidades','GOAT PRO','Preços','FAQ','Baixar app','Um único app para treino, nutrição, progresso e GOAT AI. Tudo o que precisa para manter a consistência.',' &nbsp; Baixar na App Store','▶ &nbsp; Ver funcionalidades','Treino. Nutrição. Progresso. IA. Um sistema integrado em vez de ferramentas separadas.']
};
const common={
 en:['Workout plan generator','Meal plan generator','Physique analysis from a photo','Product scanner and Meal Scan','Personalized recommendations','REAL DATA. REAL PROGRESS.','See what really drives your results.','Training, nutrition, measurements and activity come together into one clear picture of your consistency.','GOAT organized my training and nutrition. I can finally see real progress.','Track your progress, analyze results and stay motivated. GOAT shows the real picture of the work you put in.','Choose the plan that fits you.','Start free. PRO unlocks GOAT AI and premium features.','FREE','forever','Core training, nutrition and progress features.','Start for free','GOAT PRO — MONTHLY','per month','Full access to GOAT PRO and GOAT AI.','Choose monthly','BEST VALUE','GOAT PRO — YEARLY','for the whole year','Full access to GOAT PRO and GOAT AI. Best-value option.','Choose yearly','FREQUENTLY ASKED QUESTIONS','What is GOAT?','GOAT combines training, nutrition, progress tracking and AI.','Can I cancel my subscription?','Yes. You manage your subscription through your Apple account.','Is the app free?','Yes. Core features are free, while GOAT PRO unlocks premium features.','Is the app available on iOS and Android?','GOAT is currently prepared for iOS. Information about additional platforms will appear here.','Product','Help','Contact','Terms','Privacy Policy','Delete account','Download app'],
 de:['Trainingsplan-Generator','Ernährungsplan-Generator','Körperanalyse per Foto','Produktscanner und Meal Scan','Individuelle Empfehlungen','ECHTE DATEN. ECHTER FORTSCHRITT.','Sieh, was wirklich Ergebnisse bringt.','Training, Ernährung, Maße und Aktivität ergeben ein klares Bild deiner Regelmäßigkeit.','GOAT hat mein Training und meine Ernährung geordnet. Endlich sehe ich echten Fortschritt.','Verfolge deinen Fortschritt, analysiere Ergebnisse und bleib motiviert.','Wähle den Plan, der zu dir passt.','Kostenlos starten. PRO schaltet GOAT AI und Premium-Funktionen frei.','KOSTENLOS','für immer','Grundfunktionen für Training, Ernährung und Fortschritt.','Kostenlos starten','GOAT PRO — MONATLICH','pro Monat','Voller Zugriff auf GOAT PRO und GOAT AI.','Monatlich wählen','BESTER WERT','GOAT PRO — JÄHRLICH','für das ganze Jahr','Voller Zugriff auf GOAT PRO und GOAT AI.','Jährlich wählen','HÄUFIG GESTELLTE FRAGEN','Was ist GOAT?','GOAT verbindet Training, Ernährung, Fortschritt und AI.','Kann ich mein Abo kündigen?','Ja. Du verwaltest dein Abo über dein Apple-Konto.','Ist die App kostenlos?','Ja. Die Grundfunktionen sind kostenlos.','Gibt es die App für iOS und Android?','GOAT ist derzeit für iOS vorbereitet. Weitere Plattformen folgen.','Produkt','Hilfe','Kontakt','Nutzungsbedingungen','Datenschutz','Konto löschen','App laden']
};
function apply(code){
 document.documentElement.lang=code; localStorage.setItem('goatLang',code);
 nodes.forEach((el,i)=>el.innerHTML=original.get(i));
 const a=T[code]; if(!a) return;
 for(let i=0;i<a.length && i<nodes.length;i++) nodes[i].innerHTML=a[i];
 // For EN/DE, translate remaining major copy using sequential supplemental values.
 const c=common[code]; if(c){ const start=16; for(let j=0;j<c.length && start+j<nodes.length;j++) nodes[start+j].innerHTML=c[j]; }
}
if(lang){const saved=localStorage.getItem('goatLang')||'pl'; lang.value=saved; apply(saved); lang.addEventListener('change',e=>apply(e.target.value));}
